name: Print Tag and Fetch Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Enter the Docker image tag"
        required: true
        type: string
        default: "latest"

jobs:
  print_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Print only the tag
        run: echo "${{ github.event.inputs.tag }}"

      - name: Pull Docker Image
        run: |
          echo "Pulling Docker image with tag: ${{ github.event.inputs.tag }}"
          docker pull ghcr.io/himanshp1656/newsnblog:${{ github.event.inputs.tag }}
