name: Print Name Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        required: true
        default: "User"

jobs:
  print_name:
    runs-on: ubuntu-latest

    steps:
      - name: Print name parameter
        run: echo "Triggered by: ${{ github.event.inputs.name }}"
