name: Print Name and Fetch Docker Image

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter the Docker image name"
        required: true
        type: string
        default: "newsnblog"
      tag:
        description: "Enter the Docker image tag"
        required: true
        type: string
        default: "latest"

jobs:
  fetch_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Print Docker Image Name and Tag
        run: |
          echo "${{ github.event.inputs.name }}"
          echo "${{ github.event.inputs.tag }}"

      - name: Pull Docker Image
        run: |
          echo "Pulling Docker image: ghcr.io/himanshp1656/${{ github.event.inputs.name }}:${{ github.event.inputs.tag }}"
          docker pull ghcr.io/himanshp1656/${{ github.event.inputs.name }}:${{ github.event.inputs.tag }}
