name: Print Name and Pull Docker Image from GAR

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter the full Docker image path"
        required: true
        type: string
        default: "asia-south1-docker.pkg.dev/swarna-380521/docker-staging/hello-app:1.0"

jobs:
  print_name:
    runs-on: ubuntu-latest

    steps:
      - name: Print only the name
        run: echo "${{ github.event.inputs.name }}"

      - name: Install Google Cloud SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk

      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GCR_JSON_KEY }}" > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Pull Docker Image from GAR
        run: |
          echo "Pulling Docker image: ${{ github.event.inputs.name }}"
          docker pull ${{ github.event.inputs.name }}
